version: '3.8'

services:
  vin-scanner-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vin-scanner-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_PATH=/data/vehicles.db
    volumes:
      - vin_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  vin_data:
    driver: local