version: '3.8'

services:
  vin-scanner-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vin-scanner-server
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_PATH=/data/vehicles.db
    volumes:
      - vin_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - vin-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: vin-scanner-nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-admin@visiontechadas.duckdns.org}
    volumes:
      - letsencrypt_data:/etc/letsencrypt
      - certbot_webroot:/var/www/certbot
    depends_on:
      - vin-scanner-api
    restart: unless-stopped
    networks:
      - vin-network

volumes:
  vin_data:
    driver: local
  letsencrypt_data:
    driver: local
  certbot_webroot:
    driver: local

networks:
  vin-network:
    driver: bridge